### PR TITLE
Feat code actions

### LINKED ISSUE #3: Surface Ruff auto-fix capabilities as Quick Fix actions

### PR DESCRIPTION
**Pull request by betaboon**
resolves #3 

i tried my hand at surfacing the fixes that ruff proposes as code-actions.

i didn't yet add a fixAll action, as i was unsure about the semantics:
- should "fixall" apply only to all the fixes on the currently selected line or on the whole file?

### CODE REVIEW

**Comment by betaboon** [comment]
on the topic of code-action vs formatting:

I'm coming from `pyls-isort` which implements import-sorting as `textDocument/formatting` and i got very used to having an `autocmd` that runs `vim.lsp.buf.format` on save.

I'm wondering if `python-lsp-ruff` should also implement a `textDocument/formatting` but only apply a limited subset of all of ruffs proposed fixes, eg import-sorting due to `I001`.

any opinions on that ?

**Comment by jhossbach** [comment]
Nice changes!
On the semantics: "Fixall" is supposed to format the whole document, not just the current line.

On the formatting vs. code action part:
I had asked a similar question in #3, I like the idea of using formatting to e.g. sort imports.
Ruff-LSP has the specific code action "Fix imports" for that, but I think we can do one better and let the user specify a set of fixable errors that should be fixed during formatting.
We could call this option `ruff.formatCodes`.
We also need to think about the default codes, either we completely let the user decide or we select a set of codes. What do you think?

**Comment by betaboon** [comment]
thanks for the quick response.

(sorry in advance for the amount of text)


i would like to keep the scope of this PR as it is (that is, exposing the individual fixes as proposed by ruff).

i would be willing to send some more PRs, some ideas are described further down.

## this PR

this is what i want to do in the scope of this PR:
- some tests wouldnt hurt
- the ci should pass


## fixAll

when having fixAll fix all the problems in the current file, i guess it would be best to let ruff do that itself, instead of trying to do that with `WorkspaceEdit`.

reason being: ruff already respects [fixable](https://beta.ruff.rs/docs/settings/#fixable) coming from the config. 


## formatting

i like the idea of `formatCodes`.
maybe calling it `format` would keep it consistent with `ignore` and `select` tho?

regarding the default-codes, i think it makes sense to define a default for the `formatCodes` that can then be overridden by the user. (eg just `[ "I" ]`?)


## repo "improvements"

I'm proposing the following changes to the repo itself:
- replace isort in pre-commit config with ruff
- replace `setup.py`+setuptools with `pdm` for dependency-pinning and building
- setup ci to automatically build+release to pypi after merge to main (including changelog generation)


## code improvements

Since mypy is a already setup in pre-commit, I'm proposing:
- setting mypy to strict via `pyproject.toml`
- getting the codebase mypy-happy
- using dataclasses or typeddicts for all the json structures.

**Comment by jhossbach** [comment]
Nice ideas in all, let's create new issues from your ideas to discuss. Specifically for the code base improvements I think we should discuss this to be done in `python-lsp-server` as well rather than just `python-lsp-ruff`.
Same for using `pdm` which I am unfamiliar with.

**Comment by jhossbach** [comment]
You're right about the "Fix All" part, but we should nevertheless respect the user pylsp config settings, e.g. `extendIgnore`.
As for the formatting I have nothing to add except that we can disable formatting from ruff if the list ia aet to be empty.

**Comment by jhossbach** [comment]
I'll start creating some issues.

**Comment by betaboon** [comment]
fyi: i just found out about [lsprotocol](https://github.com/microsoft/lsprotocol/tree/main/packages/python) which is coming from upstream (microsoft), also uses `cattrs` for serialization and has all the classes for the payloads defined.

so i changed this PR accordingly

**Comment by jhossbach** [comment]
Yeah, `ruff-lsp` uses the same package. I wanted to play around with it for a while now, and I'd love to see `pylsp` being written with that in the future

**Comment by betaboon** [comment]
ok. this now has some more code-actions:
- fix code
- disable code
- organize imports
- fix all

**Comment by jhossbach** [comment]
Hmm, for some reason I can't reproduce the issue that mypy is reporting even when using 3.8. Not sure whether this poses a problem, but we should fix testing first

**Comment by jhossbach** [comment]
Yeah , good idea moving the code format to another PR.
I fixed the tests on my side, but the Github runners seem not to agree with me. The problem before was that `run_ruff` returns a str that is not understood by the `cattrs` converter. `json.loads` works, but it expects the string not to be empty, thus requiring the check before parsing.
Can you see if you find the problem?

**Comment by jhossbach** [comment]
Found the issue... `ruff v0.0.260` introduced a regression. I suspect a different syntax in the `json` format output but I'll look into it now.

**Comment by jhossbach** [comment]
I reverted from using `__future__.annotations` as this created the issues.

**Comment by jhossbach** [comment]
I added some tests for the code actions, PTAL if you see anything else @betaboon

**Comment by betaboon** [comment]
I'm just coming back to this seeing that you got pretty much everything done. awesome. thanks a bunch.

I'm still curious why `from __future__ import annotations` doesnt seem to work.
I'm using that in all my projects and that just works :/

**Comment by jhossbach** [comment]
Sorry, I forgot to push the new tests. Please review the unit tests if anything is missing

**Comment by betaboon** [comment]
i cleaned up the branch.
i think it's ready now.

**Comment by Shane-XB-Qian** [comment]
seems it did not support kinds  of err, right?
e.g:
```python
def f():
    pass


ff()
```

would not prompt code action for `ff()`.

**Comment by jhossbach** [comment]
That's because `ruff` doesn't provide any fixes for `ff()`, see https://beta.ruff.rs/docs/rules/ for a list of rules that are fixable

**Pull request merged**
